---
apiVersion: v1
kind: ReplicationController
metadata:
  name: capstone-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: capstone
        role: blue
    spec:
      containers:
      - name: capstone-container
        image: moussa89/capstone
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
