---
kind: Service
apiVersion: v1
metadata:
  name: capstone-service
  labels:
    app: capstone
    role: blue
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: capstone
    role: blue
  ports:
    - port: 80
      targetPort: 8080
