---
kind: ReplicationController
apiVersion: v1
metadata:
    name: capstone-blue
    labels:
        app: capstone-blue
spec:
    replicas: 1
    selector:
        app: capstone-blue
    template:
        metadata:
            labels:
                app: capstone-blue
        spec:
            containers:
                - name: capstone-blue
                  image: moussa89/capstone
                  ports:
                      - name: http-server
                        containerPort: 80

