---
apiVersion: v1
kind: ReplicationController
metadata:
  name: capstone-green
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: capstone-green
        role: green
    spec:
      containers:
      - name: capstone-container-green
        image: moussa89/capstone
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
