---
kind: ReplicationController
apiVersion: v1
metadata:
    name: capstone-green
    labels:
        app: capstone-green
spec:
    replicas: 1
    selector:
        app: green
    template:
        metadata:
            labels:
                app: capstone-green
        spec:
            containers:
                - name: capstone-green
                  image: moussa89/capstone
                  ports:
                      - name: http-server
                        containerPort: 80

